### PR TITLE
update code verification and add quality highliting

### PR DESCRIPTION
**Pull request by leonardpahlke**
Signed-off-by: leonardpahlke <leonard.pahlke@googlemail.com>

### Proposed changes

* fix: verification does not update dependencies
* docs: add badges
* feat: action, golang code coverage comment
* fix: allow multiple kind lables on PRs

### Types of changes

What types of changes does your code introduce to Carbonaut?

/kind feature
/kind bug-fix

### Checklist

_All boxes should be checked before the PR gets merged_
- [x] I have read the [CONTRIBUTING](https://github.com/carbonaut-cloud/community/blob/main/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if done in a separate PR link to it in the comments section)
- [x] I don't have a merge commit in my history (see [git merge documentation](https://www.git-scm.com/docs/git-merge#_options)) (if applicable)
- [x] I signed all my commits (see [how to sign commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits))

#### Which issue(s) this PR fixes:

`None`

## Comments

`None`

### CODE REVIEW

**Comment by leonardpahlke** [comment]
/cc @mkorbi 

code coverage: https://coveralls.io/github/carbonaut-cloud/carbonaut

**Comment by carbonautMustache** [comment]
Code coverage link:

**Comment by leonardpahlke** [comment]
Ready for review

**Pull request merged**
